image: maven:3.5.4-jdk-8

maven:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  before_script:
    - mkdir -p /cache/m2
    - ln -s /cache/m2 ~/.m2/repository || true
  script: mvn clean install -DskipTests
  artifacts:
    paths:
      - target/SaraServer-*.war

postgres:
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  image: postgres:10.4
  script:
    - pg_createcluster --start 10 main -- --nosync
    - gosu postgres saradb/createdb.sh sara sara test </dev/null
    - gosu postgres pg_dump --no-password --serializable-deferrable 
      --quote-all-identifiers --no-tablespaces --no-owner --encoding utf8
      --format plain sara >database.sql
  artifacts:
    paths:
      - database.sql

deploy:
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - export TARGET=saradb/credentials/test.sara-service.org
    - chmod 600 $TARGET.key
    - export SSH="ssh -o UserKnownHostsFile=$TARGET.known -i $TARGET.key deploy@test.sara-service.org"
    - $SSH tomcat <target/SaraServer-*.war
    - $SSH postgres <database.sql
  only:
    - test
