/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bwfdm.sara.gui;

import bwfdm.sara.publication.dspace.dto.MetadataEntryObjectDSpace;
import bwfdm.sara.publication.dspace.dto.MetadataConstantsDSpace;
import bwfdm.sara.publication.dspace.DSpaceConfig;
import bwfdm.sara.publication.OparuFive;
import bwfdm.sara.publication.dspace.dto.CollectionObjectDSpaceSix;
import bwfdm.sara.publication.dspace.dto.CommunityObjectDSpaceSix;
import bwfdm.sara.publication.dspace.dto.ItemObjectDSpaceSix;
import bwfdm.sara.utils.JsonUtils;

/**
 *
 * @author vk
 */
public class TestForm extends javax.swing.JFrame {

    /**
     * Creates new form TestForm
     */
    public TestForm() {
        initComponents();
        textAreaOutput.setEditable(true);
        rbtnOparuSix.setSelected(true);
        buttonGroup1.add(rbtnOparuFive);
        buttonGroup1.add(rbtnOparuSix);                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanelButtons = new javax.swing.JPanel();
        panelRest = new javax.swing.JPanel();
        btnRestTest = new javax.swing.JButton();
        btnConnectionStatus = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        panelCommunity = new javax.swing.JPanel();
        btnCreateCommunity = new javax.swing.JButton();
        btnGetAllCommunities = new javax.swing.JButton();
        btnGetCommunityById = new javax.swing.JButton();
        btnDeleteCommunity = new javax.swing.JButton();
        btnUpdateCommunity = new javax.swing.JButton();
        panelCollections = new javax.swing.JPanel();
        btnCreateCollection = new javax.swing.JButton();
        btnGetCollectionById = new javax.swing.JButton();
        btnGetAllCollections = new javax.swing.JButton();
        btnDeleteCollection = new javax.swing.JButton();
        btnUpdateCollection = new javax.swing.JButton();
        panelItems = new javax.swing.JPanel();
        btnGetAllItems = new javax.swing.JButton();
        btnGetItemById = new javax.swing.JButton();
        btnCreateItem = new javax.swing.JButton();
        btnGetItemIdMetadata = new javax.swing.JButton();
        btnAddItemMetadata = new javax.swing.JButton();
        btnUpdateItemMetadata = new javax.swing.JButton();
        btnClearItemMetadata = new javax.swing.JButton();
        btnDeleteItem1 = new javax.swing.JButton();
        btnGetAllBitstreamsItem = new javax.swing.JButton();
        btnAdditemBitstream = new javax.swing.JButton();
        btnDeleteItemBitstream = new javax.swing.JButton();
        panelPublicationRepo = new javax.swing.JPanel();
        btnLoginPubRepo = new javax.swing.JButton();
        btnLogoutPubRepo = new javax.swing.JButton();
        panelBitstreams = new javax.swing.JPanel();
        btnGetAllBitstreams = new javax.swing.JButton();
        btnGetBitstreamById = new javax.swing.JButton();
        jPanelOutput = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaOutput = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        rbtnOparuFive = new javax.swing.JRadioButton();
        rbtnOparuSix = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 900));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelButtons.setLayout(new java.awt.GridBagLayout());

        panelRest.setBorder(javax.swing.BorderFactory.createTitledBorder("REST"));
        panelRest.setLayout(new java.awt.GridBagLayout());

        btnRestTest.setText("REST-test");
        btnRestTest.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRestTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestTestActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelRest.add(btnRestTest, gridBagConstraints);

        btnConnectionStatus.setText("Connection status");
        btnConnectionStatus.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConnectionStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectionStatusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelRest.add(btnConnectionStatus, gridBagConstraints);

        btnLogin.setText("Login");
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelRest.add(btnLogin, gridBagConstraints);

        btnLogout.setText("Logout");
        btnLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelRest.add(btnLogout, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelButtons.add(panelRest, gridBagConstraints);

        panelCommunity.setBorder(javax.swing.BorderFactory.createTitledBorder("Community"));
        panelCommunity.setLayout(new java.awt.GridBagLayout());

        btnCreateCommunity.setText("create Community (parentID, name)");
        btnCreateCommunity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCommunityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCommunity.add(btnCreateCommunity, gridBagConstraints);

        btnGetAllCommunities.setText("get all Communities");
        btnGetAllCommunities.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetAllCommunities.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllCommunitiesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCommunity.add(btnGetAllCommunities, gridBagConstraints);

        btnGetCommunityById.setText("get Community by ID");
        btnGetCommunityById.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetCommunityById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCommunityByIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCommunity.add(btnGetCommunityById, gridBagConstraints);

        btnDeleteCommunity.setText("delete Community (by ID)");
        btnDeleteCommunity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeleteCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCommunityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCommunity.add(btnDeleteCommunity, gridBagConstraints);

        btnUpdateCommunity.setText("update Community (ID, new name)");
        btnUpdateCommunity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdateCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCommunityActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCommunity.add(btnUpdateCommunity, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelButtons.add(panelCommunity, gridBagConstraints);

        panelCollections.setBorder(javax.swing.BorderFactory.createTitledBorder("Collection"));
        panelCollections.setLayout(new java.awt.GridBagLayout());

        btnCreateCollection.setText("create Collection");
        btnCreateCollection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCollectionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCollections.add(btnCreateCollection, gridBagConstraints);

        btnGetCollectionById.setText("get Collection by ID");
        btnGetCollectionById.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetCollectionById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetCollectionByIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCollections.add(btnGetCollectionById, gridBagConstraints);

        btnGetAllCollections.setText("get all Collections");
        btnGetAllCollections.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetAllCollections.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllCollectionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCollections.add(btnGetAllCollections, gridBagConstraints);

        btnDeleteCollection.setText("delete Collection (ID)");
        btnDeleteCollection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeleteCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCollectionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCollections.add(btnDeleteCollection, gridBagConstraints);

        btnUpdateCollection.setText("update Collection (ID, new name)");
        btnUpdateCollection.setToolTipText("");
        btnUpdateCollection.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdateCollection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCollectionActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelCollections.add(btnUpdateCollection, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelButtons.add(panelCollections, gridBagConstraints);

        panelItems.setBorder(javax.swing.BorderFactory.createTitledBorder("Item"));
        panelItems.setLayout(new java.awt.GridBagLayout());

        btnGetAllItems.setText("get all Items");
        btnGetAllItems.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetAllItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllItemsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnGetAllItems, gridBagConstraints);

        btnGetItemById.setText("get Item by ID");
        btnGetItemById.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetItemById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetItemByIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnGetItemById, gridBagConstraints);

        btnCreateItem.setText("create Item");
        btnCreateItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCreateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateItemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnCreateItem, gridBagConstraints);

        btnGetItemIdMetadata.setText("get Item ID metadata");
        btnGetItemIdMetadata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetItemIdMetadata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetItemIdMetadataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnGetItemIdMetadata, gridBagConstraints);

        btnAddItemMetadata.setText("add Item metadata");
        btnAddItemMetadata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAddItemMetadata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemMetadataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnAddItemMetadata, gridBagConstraints);

        btnUpdateItemMetadata.setText("update Item metadata");
        btnUpdateItemMetadata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnUpdateItemMetadata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateItemMetadataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnUpdateItemMetadata, gridBagConstraints);

        btnClearItemMetadata.setText("clear Item metadata");
        btnClearItemMetadata.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnClearItemMetadata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearItemMetadataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnClearItemMetadata, gridBagConstraints);

        btnDeleteItem1.setText("delete Item");
        btnDeleteItem1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeleteItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItem1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnDeleteItem1, gridBagConstraints);

        btnGetAllBitstreamsItem.setText("get Item Bitstreams");
        btnGetAllBitstreamsItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetAllBitstreamsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllBitstreamsItemActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnGetAllBitstreamsItem, gridBagConstraints);

        btnAdditemBitstream.setText("add Item Bitstream");
        btnAdditemBitstream.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAdditemBitstream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdditemBitstreamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnAdditemBitstream, gridBagConstraints);

        btnDeleteItemBitstream.setText("delete Item Btstream");
        btnDeleteItemBitstream.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnDeleteItemBitstream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemBitstreamActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelItems.add(btnDeleteItemBitstream, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelButtons.add(panelItems, gridBagConstraints);

        panelPublicationRepo.setBorder(javax.swing.BorderFactory.createTitledBorder("Publication Repository"));
        panelPublicationRepo.setLayout(new java.awt.GridBagLayout());

        btnLoginPubRepo.setText("Login");
        btnLoginPubRepo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLoginPubRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginPubRepoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPublicationRepo.add(btnLoginPubRepo, gridBagConstraints);

        btnLogoutPubRepo.setText("Logout");
        btnLogoutPubRepo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnLogoutPubRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutPubRepoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelPublicationRepo.add(btnLogoutPubRepo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelButtons.add(panelPublicationRepo, gridBagConstraints);

        panelBitstreams.setBorder(javax.swing.BorderFactory.createTitledBorder("Bitstream"));
        panelBitstreams.setLayout(new java.awt.GridBagLayout());

        btnGetAllBitstreams.setText("get all Bitstreams");
        btnGetAllBitstreams.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetAllBitstreams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetAllBitstreamsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelBitstreams.add(btnGetAllBitstreams, gridBagConstraints);

        btnGetBitstreamById.setText("get Bitstream by ID");
        btnGetBitstreamById.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGetBitstreamById.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetBitstreamByIdActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        panelBitstreams.add(btnGetBitstreamById, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jPanelButtons.add(panelBitstreams, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanelButtons, gridBagConstraints);

        jPanelOutput.setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        textAreaOutput.setColumns(20);
        textAreaOutput.setRows(5);
        textAreaOutput.setText("Text is here\n\n\n\n\n\n\n\n\n\n\nyo!");
        textAreaOutput.setMinimumSize(new java.awt.Dimension(180, 220));
        textAreaOutput.setPreferredSize(null);
        jScrollPane1.setViewportView(textAreaOutput);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelOutput.add(jPanel1, gridBagConstraints);

        jLabel1.setText("ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelOutput.add(jLabel1, gridBagConstraints);

        rbtnOparuFive.setText("OPARU-5");
        rbtnOparuFive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOparuFiveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanelOutput.add(rbtnOparuFive, gridBagConstraints);

        rbtnOparuSix.setText("OPARU-6");
        rbtnOparuSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnOparuSixActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanelOutput.add(rbtnOparuSix, gridBagConstraints);

        jLabel2.setText("Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelOutput.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelOutput.add(tfID, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanelOutput.add(tfName, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 125;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanelOutput, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRestTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestTestActionPerformed
        String str = MainInt.testRest();
        textAreaOutput.setText(str);
    }//GEN-LAST:event_btnRestTestActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String str = MainInt.loginDspace();
        textAreaOutput.setText(str);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        String str = MainInt.logoutDspace();
        textAreaOutput.setText(str);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnConnectionStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectionStatusActionPerformed
        String str = MainInt.getConnectionStatus();
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnConnectionStatusActionPerformed

    private void btnGetAllCommunitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllCommunitiesActionPerformed
        String str = MainInt.getAllCommunities();       
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
        
        // Convert String-Object-String (test)
        CommunityObjectDSpaceSix[] obj = JsonUtils.jsonStringToObject(str, CommunityObjectDSpaceSix[].class);
        String strConverted = JsonUtils.objectToJsonString(obj);
        System.out.println(JsonUtils.jsonStringPrettyPrint(strConverted));
    }//GEN-LAST:event_btnGetAllCommunitiesActionPerformed

    private void btnGetCommunityByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCommunityByIdActionPerformed
        String id = tfID.getText();
        String str = MainInt.getCommunityById(id);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
        
        // Convert String-Object-String (test)
        CommunityObjectDSpaceSix obj = JsonUtils.jsonStringToObject(str, CommunityObjectDSpaceSix.class);
        String strConverted = JsonUtils.objectToJsonString(obj);
        System.out.println(JsonUtils.jsonStringPrettyPrint(strConverted));
    }//GEN-LAST:event_btnGetCommunityByIdActionPerformed

    private void btnCreateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCommunityActionPerformed
        String idParent = tfID.getText();
        String name = tfName.getText();
        String str = MainInt.createCommunity(name, idParent);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnCreateCommunityActionPerformed

    private void btnGetAllCollectionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllCollectionsActionPerformed
        String str = MainInt.getAllCollections();
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
        
        // Convert String-Object-String (test)
        CollectionObjectDSpaceSix[] obj = JsonUtils.jsonStringToObject(str, CollectionObjectDSpaceSix[].class);
        String strConverted = JsonUtils.objectToJsonString(obj);
        System.out.println(JsonUtils.jsonStringPrettyPrint(strConverted));
    }//GEN-LAST:event_btnGetAllCollectionsActionPerformed

    private void btnGetCollectionByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetCollectionByIdActionPerformed
        String id = tfID.getText();
        String str = MainInt.getCollectionById(id);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnGetCollectionByIdActionPerformed

    private void btnCreateCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCollectionActionPerformed
        String idParent = tfID.getText();
        String name = tfName.getText();
        String str = MainInt.createCollection(name, idParent);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnCreateCollectionActionPerformed

    private void btnCreateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateItemActionPerformed
        String idCollection = tfID.getText();
        String name = tfName.getText();
        String str = MainInt.createItem(name, "test-item-titel", idCollection);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnCreateItemActionPerformed

    private void btnGetAllItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllItemsActionPerformed
        String str = MainInt.getAllItems();
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
        
        // Convert String-Object-String (test)
        ItemObjectDSpaceSix[] obj = JsonUtils.jsonStringToObject(str, ItemObjectDSpaceSix[].class);
        String strConverted = JsonUtils.objectToJsonString(obj);
        System.out.println(JsonUtils.jsonStringPrettyPrint(strConverted));
    }//GEN-LAST:event_btnGetAllItemsActionPerformed

    private void btnGetItemByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetItemByIdActionPerformed
        String id = tfID.getText();
        String str = MainInt.getItemById(id);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnGetItemByIdActionPerformed

    private void btnGetAllBitstreamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllBitstreamsActionPerformed
        String str = MainInt.getAllBitstreams();
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnGetAllBitstreamsActionPerformed

    private void btnDeleteCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCommunityActionPerformed
        String idCommunity = tfID.getText();
        String str = MainInt.deleteCommunity(idCommunity);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnDeleteCommunityActionPerformed

    private void btnUpdateCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCommunityActionPerformed
        String idCommunity = tfID.getText();
        String newName = tfName.getText();
        String str = MainInt.updateCommunity(newName, idCommunity);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnUpdateCommunityActionPerformed

    private void btnDeleteCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCollectionActionPerformed
        String idCollection = tfID.getText();
        String str = MainInt.deleteCollection(idCollection);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnDeleteCollectionActionPerformed

    private void btnUpdateCollectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCollectionActionPerformed
        String idCollection = tfID.getText();
        String newName = tfName.getText();
        String str = MainInt.updateCollection(newName, idCollection);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnUpdateCollectionActionPerformed

    private void btnGetItemIdMetadataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetItemIdMetadataActionPerformed
        String id = tfID.getText();
        String str = MainInt.getItemMetadataById(id);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnGetItemIdMetadataActionPerformed

    private void rbtnOparuFiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOparuFiveActionPerformed
        MainInt.chooseOparuFive();        
    }//GEN-LAST:event_rbtnOparuFiveActionPerformed

    private void rbtnOparuSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnOparuSixActionPerformed
        MainInt.chooseOparuSix();
    }//GEN-LAST:event_rbtnOparuSixActionPerformed

    private void btnAddItemMetadataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemMetadataActionPerformed
        
        // test item: 70dd4e09-0148-499e-b772-06e88414c16a
        
        String metadata = getDataFromDialog(JsonUtils.jsonStringPrettyPrint(MetadataConstantsDSpace.ITEM_METADATA_EXAMPLE));
        
        // Convert String metadata to Object
        MetadataEntryObjectDSpace[] metadataObj;
        metadataObj = JsonUtils.jsonStringToObject(metadata, MetadataEntryObjectDSpace[].class);
        // Convert Object with metadata to the String
        String metadataConverted = JsonUtils.objectToJsonString(metadataObj);
        System.out.println(JsonUtils.jsonStringPrettyPrint(metadataConverted));
        
        // REST-Request, change metadata
        String id = tfID.getText();
        String str = MainInt.addItemMetadata(id, metadataConverted);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnAddItemMetadataActionPerformed

    private void btnUpdateItemMetadataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateItemMetadataActionPerformed
        String metadata = getDataFromDialog(JsonUtils.jsonStringPrettyPrint(MetadataConstantsDSpace.ITEM_METADATA_EXAMPLE));
        
        // Convert String metadata to Object
        MetadataEntryObjectDSpace[] metadataObj;
        metadataObj = JsonUtils.jsonStringToObject(metadata, MetadataEntryObjectDSpace[].class);
        // Convert Object with metadata to the String
        String metadataConverted = JsonUtils.objectToJsonString(metadataObj);
        System.out.println(JsonUtils.jsonStringPrettyPrint(metadataConverted));
        
        // REST-Request, change metadata
        String id = tfID.getText();
        String str = MainInt.updateItemMetadata(id, metadataConverted);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnUpdateItemMetadataActionPerformed

    private void btnClearItemMetadataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearItemMetadataActionPerformed
        String id = tfID.getText();
        String str = MainInt.clearItemMetadata(id);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnClearItemMetadataActionPerformed

    private void btnDeleteItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItem1ActionPerformed
        String id = tfID.getText();
        String str = MainInt.deleteItem(id);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnDeleteItem1ActionPerformed

    private void btnGetBitstreamByIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetBitstreamByIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGetBitstreamByIdActionPerformed

    private void btnGetAllBitstreamsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetAllBitstreamsItemActionPerformed
        String id = tfID.getText();
        String str = MainInt.getAllItemBitstreams(id);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnGetAllBitstreamsItemActionPerformed

    private void btnAdditemBitstreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdditemBitstreamActionPerformed
        String bitstreamDescription = getDataFromDialog(JsonUtils.jsonStringPrettyPrint(MetadataConstantsDSpace.ITEM_BITSTREAM_DESCRIPTION_EXAMPLE));
        String itemId = tfID.getText();
        String str = MainInt.itemAddBitstream(itemId, bitstreamDescription);
        textAreaOutput.setText(JsonUtils.jsonStringPrettyPrint(str));
    }//GEN-LAST:event_btnAdditemBitstreamActionPerformed

    private void btnDeleteItemBitstreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemBitstreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteItemBitstreamActionPerformed

    private void btnLoginPubRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginPubRepoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginPubRepoActionPerformed

    private void btnLogoutPubRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutPubRepoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutPubRepoActionPerformed

    
    private String getDataFromDialog(String text){
        ChangeDataDialog metadataDialog = new ChangeDataDialog(this, true, text);
        metadataDialog.setLocationRelativeTo(this);
        metadataDialog.setVisible(true);   
        String metadata = metadataDialog.getText(); // get metadata from the Dialog 
        return metadata;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItemMetadata;
    private javax.swing.JButton btnAdditemBitstream;
    private javax.swing.JButton btnClearItemMetadata;
    private javax.swing.JButton btnConnectionStatus;
    private javax.swing.JButton btnCreateCollection;
    private javax.swing.JButton btnCreateCommunity;
    private javax.swing.JButton btnCreateItem;
    private javax.swing.JButton btnDeleteCollection;
    private javax.swing.JButton btnDeleteCommunity;
    private javax.swing.JButton btnDeleteItem1;
    private javax.swing.JButton btnDeleteItemBitstream;
    private javax.swing.JButton btnGetAllBitstreams;
    private javax.swing.JButton btnGetAllBitstreamsItem;
    private javax.swing.JButton btnGetAllCollections;
    private javax.swing.JButton btnGetAllCommunities;
    private javax.swing.JButton btnGetAllItems;
    private javax.swing.JButton btnGetBitstreamById;
    private javax.swing.JButton btnGetCollectionById;
    private javax.swing.JButton btnGetCommunityById;
    private javax.swing.JButton btnGetItemById;
    private javax.swing.JButton btnGetItemIdMetadata;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLoginPubRepo;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnLogoutPubRepo;
    private javax.swing.JButton btnRestTest;
    private javax.swing.JButton btnUpdateCollection;
    private javax.swing.JButton btnUpdateCommunity;
    private javax.swing.JButton btnUpdateItemMetadata;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelButtons;
    private javax.swing.JPanel jPanelOutput;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelBitstreams;
    private javax.swing.JPanel panelCollections;
    private javax.swing.JPanel panelCommunity;
    private javax.swing.JPanel panelItems;
    private javax.swing.JPanel panelPublicationRepo;
    private javax.swing.JPanel panelRest;
    private javax.swing.JRadioButton rbtnOparuFive;
    private javax.swing.JRadioButton rbtnOparuSix;
    private javax.swing.JTextArea textAreaOutput;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables
}
